rules:
  document-end: disable
  document-start:
    level: ignore
    present: false
  line-length:
    level: warning
    max: 250
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
